apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: k8s-openbao
  annotations:
    github.com/project-slug: mattjmorrison-homelab/k8s-openbao
spec:
  type: secret-store
  owner: mattjmorrison-homelab
  system: platform
